version: '3'

services:
  bot:
    command: "python main.py"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    volumes:
    - .:/bot