version: '3'

services:
  bot:
    command: "python3 main.py"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    volumes:
    - ./vmd/:/bot/vmd